# Generated by Django 4.2.14 on 2024-07-13 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('ingredients', models.TextField()),
                ('instructions', models.TextField()),
                ('imgURL', models.URLField(blank=True, null=True)),
                ('time', models.PositiveIntegerField(help_text='Time in minutes')),
                ('servings', models.PositiveIntegerField()),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
